<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>Nexotool</Company>
    <Authors>Nexotool</Authors>
    <Copyright>© Nexotool</Copyright>
    <Version>2.2.0</Version>
    <!-- Permite compilar os projetos WPF fora do Windows (CI/nuvem). -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SatelliteResourceLanguages>pt-BR</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
