export const adminTexts = {
  title: "Painel administrativo",
  subtitle: "Emita licenças, acompanhe ativações e gerencie o acesso dos clientes.",
  accessDeniedTitle: "Acesso administrativo não liberado",
  accessDeniedText: "Você está conectado, mas este e-mail ainda não está marcado como administrador.",
  accessDeniedSql: "No Neon SQL Editor, atualize public.profiles e defina role = 'admin' para este e-mail (ou inclua-o em ADMIN_EMAILS). Depois saia e entre novamente.",
  currentEmail: "E-mail atual",
  currentRole: "Função atual",
  licenseSearch: "Buscar licença",
  licenseSearchPlaceholder: "Busque por e-mail, chave, máquina, IP, pedido ou status",
  createLicense: "Emitir licença",
  generateLicenseShort: "Gerar licença",
  manualTitle: "Emissão manual de licença",
  manualText: "Informe o e-mail do cliente e gere a chave oficial. Ela aparece aqui para cópia e é enviada por e-mail quando o envio está configurado.",
  customerEmail: "E-mail do cliente",
  product: "Produto",
  maxMachines: "Máquinas",
  validity: "Validade",
  validityUnit: "Unidade",
  validityHint: "Por quanto tempo a licença será válida a partir de hoje. Deixe vazio para não vencer.",
  noExpiration: "Sem vencimento",
  days: "Dias",
  months: "Meses",
  years: "Anos",
  creating: "Gerando...",
  createSuccess: "Licença criada. Copie a chave e envie ao cliente.",
  createError: "Não foi possível criar a licença.",
  emailNotSent: "O e-mail não foi enviado automaticamente.",
  generatedKey: "Chave gerada",
  licensesTitle: "Licenças emitidas",
  activate: "Ativar",
  clearActivation: "Limpar ativação",
  revoke: "Revogar",
  block: "Bloquear",
  user: "Cliente",
  license: "Licença",
  machineName: "Nome da máquina",
  machineId: "Machine ID",
  softwareVersion: "Versão",
  activatedAt: "Ativada em",
  lastSeen: "Último acesso",
  lastValidation: "Última validação",
  lastIp: "Último IP",
  createdAt: "Criada em",
  order: "Pedido",
  expiresAt: "Vence em",
  expandHint: "Expandir ou recolher detalhes da licença",
  activateHint: "Marca a licença como ativa novamente.",
  clearActivationHint: "Remove os registros de ativação para liberar a licença para outra máquina.",
  revokeHint: "Revoga a licença e impede novas validações.",
  blockHint: "Bloqueia a licença imediatamente.",
  cancelHint: "Fecha esta confirmação sem alterar a licença.",
  confirmTitle: "Confirmar ação",
  confirmText: "Revise o resumo antes de aplicar esta operação.",
  confirm: "Confirmar",
  cancel: "Cancelar",
  actionError: "Não foi possível concluir a operação.",
  pagination: "Paginação de licenças",
  previousPage: "Anterior",
  nextPage: "Próxima",
  pageOf: "Página {page} de {total}",
  empty: "Nenhuma licença encontrada."
};

export const statusText = {
  active: "Ativa",
  revoked: "Revogada",
  blocked: "Bloqueada",
  expired: "Expirada"
};
